/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package costosdiplomado;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class frmDiplomado extends javax.swing.JFrame {

    public frmDiplomado() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtValorMatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDocencia = new javax.swing.JTextField();
        txtPlataforma = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnProyeccion = new javax.swing.JButton();
        txtAdministracion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jspGrupos = new javax.swing.JSpinner();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Ingresos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        txtValorMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(txtValorMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 60, -1));

        jLabel2.setText("Valor Diplomado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("Costos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel4.setText("Docencia:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        getContentPane().add(txtDocencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 60, -1));
        getContentPane().add(txtPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 60, -1));

        jLabel5.setText("Plataforma:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        btnProyeccion.setText("Proyeccion Ingreso-Costos");
        btnProyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProyeccionActionPerformed(evt);
            }
        });
        getContentPane().add(btnProyeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));
        getContentPane().add(txtAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 60, -1));

        jLabel6.setText("Administracion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel7.setText("Cantidad de Grupos:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        getContentPane().add(jspGrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 50, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 260, 10));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 260, 10));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 260, 10));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 260, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorMatriculaActionPerformed

    private void btnProyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProyeccionActionPerformed
        double matricula, docencia, plataforma ,admon, ingresos, costos;
        int grupos;
        String mensaje;
        
        Diplomado objDiplomado;
        matricula = Double.parseDouble(txtValorMatricula.getText());
        docencia = Double.parseDouble(txtDocencia.getText());
        admon = Double.parseDouble(txtAdministracion.getText());
        plataforma = Double.parseDouble(txtPlataforma.getText());
        grupos = (int) jspGrupos.getValue();
        
        objDiplomado = new Diplomado(matricula, docencia, plataforma, admon,  grupos);
        ingresos = objDiplomado.calcular_ingreso();
        costos = objDiplomado.calcular_gastos();
        
        lblIngresos.setText(String.valueOf(ingresos));
        lblCostos.setText(String.valueOf(costos));
        mensaje = "Ingresos: " + ingresos + " Costos: " + costos;
        JOptionPane.showMessageDialog(null,mensaje);
    }//GEN-LAST:event_btnProyeccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDiplomado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDiplomado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDiplomado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDiplomado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDiplomado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProyeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSpinner jspGrupos;
    private javax.swing.JTextField txtAdministracion;
    private javax.swing.JTextField txtDocencia;
    private javax.swing.JTextField txtPlataforma;
    private javax.swing.JTextField txtValorMatricula;
    // End of variables declaration//GEN-END:variables
}
